### ISSUE TITLE
Reduce unnecessary babel?

### ISSUE THREAD

**Issue by jedahan** [geekplux/koa2-boilerplate#1]
As per https://github.com/koajs/koa/issues/648#issuecomment-174556302 , maybe we should reduce the babel features pulled in.

**Comment by odensc** [comment]
Considering it uses async functions, people would probably expect other ES6/7 features to work, and may be confused if they don't. As far as I know, removing the other plugins wouldn't make much of a difference besides reducing download size a bit?

**Comment by geekplux** [comment]
Okay, I'll change it. :+1: 
Thanks.

**Comment by geekplux** [comment]
I dropped the "es2015", "stage-3" preset and "transform-runtime" plugin.
