### ISSUE TITLE
production use?

### ISSUE THREAD

**Issue by ralyodio** [geekplux/koa2-boilerplate#3]
Is this suitable for production? I don't see any build step.

**Comment by geekplux** [comment]
yes, there is no script for production temporarily...any advice?

**Comment by ralyodio** [comment]
I found this which looks exactly what I need:

https://github.com/babel/example-node-server

should build to `./dist`

**Comment by Debiancc** [comment]
@geekplux 
should remove babel-register in production env
it's look like V8 JIT, compile code should not in application runtime

**Comment by geekplux** [comment]
@Debiancc thanks for your advice. This project is created 3 years ago in order to try koa2. now it's outdated, I will mark it `[Deprecated]` on introduction.
